In [2]:
#agrupamento com c-means
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.metrics import accuracy_score,confusion_matrix
import skfuzzy

In [5]:
iris = datasets.load_iris()
iris.data


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
r = skfuzzy.cmeans(data = iris.data.T, c=3, m=2, error=0.005, maxiter=1000, init=None)


In [8]:
previsoes_percent = r[1]
previsoes_percent

array([[1.07191473e-03, 7.50168883e-03, 6.41699641e-03, 1.01124406e-02,
        1.76788706e-03, 2.06282261e-02, 6.50705984e-03, 1.41274431e-04,
        2.19117010e-02, 5.34439979e-03, 1.02045719e-02, 2.43250867e-03,
        9.18138359e-03, 2.52447746e-02, 3.76427570e-02, 5.43225719e-02,
        1.75010542e-02, 1.05882837e-03, 3.03200861e-02, 6.65573489e-03,
        9.54539009e-03, 4.79559947e-03, 1.38363089e-02, 6.11599356e-03,
        9.84419745e-03, 7.97829828e-03, 1.57474720e-03, 2.08744018e-03,
        1.99649447e-03, 6.28609640e-03, 6.47732610e-03, 7.94329579e-03,
        2.03403335e-02, 3.23580347e-02, 4.59667344e-03, 4.80660642e-03,
        1.15678813e-02, 2.92685315e-03, 1.92401601e-02, 5.33495001e-04,
        1.68828238e-03, 4.70120590e-02, 1.52141650e-02, 6.33313194e-03,
        1.66088498e-02, 8.63579968e-03, 7.36751862e-03, 8.13019905e-03,
        7.26194764e-03, 9.19571979e-04, 5.01764799e-01, 2.07426466e-01,
        6.00725133e-01, 8.03323728e-02, 2.17892695e-01, 2.047238

In [9]:
for x in range(150):
    print(f'flor {x+1}: setosa: {previsoes_percent[0][x]:.4f}, versicolor: {previsoes_percent[1][x]:.4f}, virginica: {previsoes_percent[2][x]:.4f}')

flor 1: setosa: 0.0011, versicolor: 0.9966, virginica: 0.0023
flor 2: setosa: 0.0075, versicolor: 0.9758, virginica: 0.0167
flor 3: setosa: 0.0064, versicolor: 0.9798, virginica: 0.0138
flor 4: setosa: 0.0101, versicolor: 0.9674, virginica: 0.0225
flor 5: setosa: 0.0018, versicolor: 0.9945, virginica: 0.0038
flor 6: setosa: 0.0206, versicolor: 0.9345, virginica: 0.0448
flor 7: setosa: 0.0065, versicolor: 0.9795, virginica: 0.0140
flor 8: setosa: 0.0001, versicolor: 0.9995, virginica: 0.0003
flor 9: setosa: 0.0219, versicolor: 0.9303, virginica: 0.0477
flor 10: setosa: 0.0053, versicolor: 0.9827, virginica: 0.0119
flor 11: setosa: 0.0102, versicolor: 0.9680, virginica: 0.0218
flor 12: setosa: 0.0024, versicolor: 0.9921, virginica: 0.0054
flor 13: setosa: 0.0092, versicolor: 0.9706, virginica: 0.0202
flor 14: setosa: 0.0252, versicolor: 0.9229, virginica: 0.0518
flor 15: setosa: 0.0376, versicolor: 0.8897, virginica: 0.0726
flor 16: setosa: 0.0543, versicolor: 0.8413, virginica: 0.1044
f

In [10]:
previsoes = previsoes_percent.argmax(axis=0)
resultados = confusion_matrix(iris.target,previsoes)
resultados

array([[ 0, 50,  0],
       [ 3,  0, 47],
       [37,  0, 13]])