In [13]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from keras.models import Sequential 
from keras.layers import Dense, Dropout
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split
import numpy as np
from keras.datasets import mnist
import pandas as pd 


In [14]:
db = pd.read_csv("soybean.csv")
db.shape

(683, 36)

In [15]:
db.head(10)

date plant-stand   precip  temp hail         crop-hist area-damaged  \
0    october      normal  gt-norm  norm  yes       same-lst-yr    low-areas   
1     august      normal  gt-norm  norm  yes  same-lst-two-yrs    scattered   
2       july      normal  gt-norm  norm  yes       same-lst-yr    scattered   
3       july      normal  gt-norm  norm  yes       same-lst-yr    scattered   
4    october      normal  gt-norm  norm  yes  same-lst-two-yrs    scattered   
5  september      normal  gt-norm  norm  yes  same-lst-sev-yrs    scattered   
6  september      normal  gt-norm  norm  yes  same-lst-two-yrs    scattered   
7     august      normal  gt-norm  norm   no       same-lst-yr    scattered   
8    october      normal  gt-norm  norm  yes  same-lst-sev-yrs    scattered   
9     august      normal  gt-norm  norm  yes  same-lst-two-yrs    scattered   

     severity   seed-tmt germination  ... sclerotia fruit-pods fruit-spots  \
0  pot-severe       none      90-100  ...    absent       norm         dna   
1      severe  fungicide       80-89  ...    absent       norm         dna   
2      severe  fungicide       lt-80  ...    absent       norm         dna   
3      severe       none       80-89  ...    absent       norm         dna   
4  pot-severe       none       lt-80  ...    absent       norm         dna   
5  pot-severe       none       80-89  ...    absent       norm         dna   
6  pot-severe  fungicide      90-100  ...    absent       norm         dna   
7  pot-severe       none       lt-80  ...    absent       norm         dna   
8  pot-severe  fungicide       80-89  ...    absent       norm         dna   
9      severe       none       lt-80  ...    absent       norm         dna   

   seed mold-growth seed-discolor seed-size shriveling roots  \
0  norm      absent        absent      norm     absent  norm   
1  norm      absent        absent      norm     absent  norm   
2  norm      absent        absent      norm     absent  norm   
3  norm      absent        absent      norm     absent  norm   
4  norm      absent        absent      norm     absent  norm   
5  norm      absent        absent      norm     absent  norm   
6  norm      absent        absent      norm     absent  norm   
7  norm      absent        absent      norm     absent  norm   
8  norm      absent        absent      norm     absent  norm   
9  norm      absent        absent      norm     absent  norm   

                   class  
0  diaporthe-stem-canker  
1  diaporthe-stem-canker  
2  diaporthe-stem-canker  
3  diaporthe-stem-canker  
4  diaporthe-stem-canker  
5  diaporthe-stem-canker  
6  diaporthe-stem-canker  
7  diaporthe-stem-canker  
8  diaporthe-stem-canker  
9  diaporthe-stem-canker  

[10 rows x 36 columns]

In [16]:
x = db.iloc[:,0:35].values
y = db.iloc[:,35].values
y

array(['diaporthe-stem-canker', 'diaporthe-stem-canker',
       'diaporthe-stem-canker', 'diaporthe-stem-canker',
       'diaporthe-stem-canker', 'diaporthe-stem-canker',
       'diaporthe-stem-canker', 'diaporthe-stem-canker',
       'diaporthe-stem-canker', 'diaporthe-stem-canker', 'charcoal-rot',
       'charcoal-rot', 'charcoal-rot', 'charcoal-rot', 'charcoal-rot',
       'charcoal-rot', 'charcoal-rot', 'charcoal-rot', 'charcoal-rot',
       'charcoal-rot', 'rhizoctonia-root-rot', 'rhizoctonia-root-rot',
       'rhizoctonia-root-rot', 'rhizoctonia-root-rot',
       'rhizoctonia-root-rot', 'rhizoctonia-root-rot',
       'rhizoctonia-root-rot', 'rhizoctonia-root-rot',
       'rhizoctonia-root-rot', 'rhizoctonia-root-rot', 'phytophthora-rot',
       'phytophthora-rot', 'phytophthora-rot', 'phytophthora-rot',
       'phytophthora-rot', 'phytophthora-rot', 'phytophthora-rot',
       'phytophthora-rot', 'phytophthora-rot', 'phytophthora-rot',
       'phytophthora-rot', 'phytophthora-rot'

In [17]:
for i in range(35):
    lencoder = LabelEncoder()
    if type(x[0,i])==str:
        x[:,i] = lencoder.fit_transform(x[:,i])
x

array([[6, 2, 1, ..., 2, 1, 2],
       [2, 2, 1, ..., 2, 1, 2],
       [3, 2, 1, ..., 2, 1, 2],
       ...,
       [4, 1, 0, ..., 0, 0, 3],
       [1, 1, 0, ..., 0, 0, 3],
       [4, 1, 0, ..., 0, 0, 3]], dtype=object)

In [18]:
lencoder = LabelEncoder()
y = lencoder.fit_transform(y)
y = to_categorical(y, 19)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
x_trein, x_test, y_trein, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
print(len(x_trein), len(x_test), len(y_trein), len(y_test))

546 137 546 137


In [20]:
sc = StandardScaler()
x_trein = sc.fit_transform(x_trein)
x_test = sc.transform(x_test)
len(x_trein[0,:])

35

In [21]:
modelo = Sequential()
modelo.add(Dense(units=50, activation="relu", input_dim=35))
modelo.add(Dropout(0.2))
modelo.add(Dense(units=50, activation="relu"))
modelo.add(Dropout(0.2))
modelo.add(Dense(units=50, activation="relu"))
modelo.add(Dropout(0.2))
modelo.add(Dense(units=19, activation="softmax"))
modelo.summary()

/home/aluizioneto1918/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1769790692.991873   23848 cuda_executor.cc:1309] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1769790693.011455   23848 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 50)             │         1,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 50)             │         2,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 50)             │         2,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 19)             │           969 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,869 (30.74 KB)

 Trainable params: 7,869 (30.74 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
modelo.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
modelo.fit(x_trein, y_trein, epochs=1000, validation_data=(x_test, y_test))

Epoch 1/1000


18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.1355 - loss: 2.8553 - val_accuracy: 0.2628 - val_loss: 2.6029
Epoch 2/1000
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2985 - loss: 2.5312 - val_accuracy: 0.3139 - val_loss: 2.3945
Epoch 3/1000
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3626 - loss: 2.2717 - val_accuracy: 0.3139 - val_loss: 2.1829
Epoch 4/1000
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3810 - loss: 2.0469 - val_accuracy: 0.3504 - val_loss: 1.9672
Epoch 5/1000
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4084 - loss: 1.8662 - val_accuracy: 0.4891 - val_loss: 1.7605
Epoch 6/1000
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5037 - loss: 1.6852 - val_accuracy: 0.6131 - val_loss: 1.5493
Epoch 7/1000
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5641 - loss: 1.4864 - val_accuracy: 0.6496 - val_loss: 1.3591
Epoch 8/1000
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6172 - loss: 1.3135 - val_accuracy: 0.6569 - val_lo

In [23]:
y_pred = modelo.predict(x_test)
y_pred

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


array([[1.84828325e-12, 7.59439595e-11, 1.83499355e-10, ...,
        1.08334796e-13, 2.01000670e-17, 9.37246423e-18],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        4.97792507e-33, 0.00000000e+00, 2.70229208e-34],
       [9.99930252e-18, 3.29616967e-36, 1.08273403e-25, ...,
        2.58422239e-30, 9.10291290e-24, 7.06615736e-33],
       ...,
       [1.96375766e-19, 4.51136874e-20, 3.46998905e-16, ...,
        3.60468017e-32, 9.99999940e-01, 3.76968667e-15],
       [6.38520435e-17, 1.30242379e-18, 1.07525522e-17, ...,
        3.42254783e-21, 1.88130553e-10, 5.14502476e-16],
       [1.35612931e-14, 4.03214739e-29, 2.17296760e-20, ...,
        7.21113155e-19, 4.67774385e-23, 1.94802087e-13]], dtype=float32)

In [24]:
y_test_matrix = [np.argmax(t) for t in y_test]
y_pred_matrix = [np.argmax(t) for t in y_pred]
confusao = confusion_matrix(y_test_matrix, y_pred_matrix)
confusao

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0],
       [ 0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
         0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 0,  1,  0,  0,  0, 16,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,
         0,  0],
       [ 0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,
         0,  0],
       [ 0,  0,  0,  

In [25]:
y_trein[20] # 3

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [26]:
novo = x_trein[20]
novo = np.expand_dims(novo, axis=0)
pred = modelo.predict(novo)
pred = [np.argmax(t) for t in pred]
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


[np.int64(3)]