In [3]:
import numpy as np

In [8]:
mint = np.array([10, 22, 12])
print(mint)
print(type(mint))
k = [3, 4, 1, 7]
mfloat = np.array(k, dtype=np.float64)
print(mfloat)


[10 22 12]
<class 'numpy.ndarray'>
[3. 4. 1. 7.]


In [11]:
mint = np.array([10, 22, 12])
print(mint)
mint = mint.astype(np.float64)
print(mint)

mflt = np.array([3.23, 4.67898, 3.145676])
print(mflt)
mflt = mflt.astype(np.int64)
print(mflt)

[10 22 12]
[10. 22. 12.]
[3.23     4.67898  3.145676]
[3 4 3]


In [11]:
Matriz = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print(Matriz)
print(type(Matriz))

Matriz = np.empty((3,3))
print(Matriz)

Matriz = np.zeros((2,2))
print(Matriz)

Matriz = np.ones((6, 5))
print(Matriz)






[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[2.64353223e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
M = 10*np.random.random((3,4))
print(M)

M = np.random.randn(5)
print(M)

M = 2*np.random.randn(3)
print(M)



[[5.15700219 0.29392057 1.72416336 7.66458898]
 [7.07818761 0.44971621 0.2192519  6.1485695 ]
 [0.8623048  1.61886665 1.93696329 9.09246735]]
[-0.86699316 -0.59683795 -0.11938477 -1.44334712  0.35091026]
[-3.01685797 -0.86504552 -1.49178898]


In [33]:
Mk = np.random.default_rng(1)
M = Mk.random((3,5))
print(M)

M = Mk.integers(5, size=(3, 5))
print(M)


[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
 [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
 [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]]
[[0 2 4 0 1]
 [2 4 1 2 1]
 [0 3 0 1 2]]


In [34]:
m = np.array([3,3,3,3,1,1,1,1,2,4,5])
m = np.unique(m)
print(m)

[1 2 3 4 5]


In [37]:
m = np.array([[3,3,3],[3,1,1],[1,1,2]])
print(m)
print(m[0][2])
print(m.shape)

print(m.max())
print(m.min())

print(m.mean())
print(m.std())


[[3 3 3]
 [3 1 1]
 [1 1 2]]
3
(3, 3)
3
1
2.0
0.9428090415820634


In [42]:
m = np.array([3,3,3,3,1,1,1,1,2,4,5])

print(m[0:2])
print(m[0:])

print(m[2:5])
print(m[-4:11])


[3 3]
[3 3 3 3 1 1 1 1 2 4 5]
[3 3 1]
[1 2 4 5]


In [43]:
m = np.array([[3,3,3],[3,1,1],[1,1,2]])

print(m[:, 0])

print(m[2, :])



[3 3 1]
[1 1 2]


In [49]:
m = np.array([[3,3,3],[3,1,1],[1,1,2]])
n = 10*np.random.random((3,3))
print(m)
print(n)
u = m*n
print(u)
v = m+n
print(v)

[[3 3 3]
 [3 1 1]
 [1 1 2]]
[[4.89669282 6.14172315 9.5971768 ]
 [9.83506138 2.88014004 8.30567839]
 [9.65423652 7.46278497 6.93651489]]
[[14.69007847 18.42516946 28.79153039]
 [29.50518415  2.88014004  8.30567839]
 [ 9.65423652  7.46278497 13.87302979]]
[[ 7.89669282  9.14172315 12.5971768 ]
 [12.83506138  3.88014004  9.30567839]
 [10.65423652  8.46278497  8.93651489]]


In [50]:
m = np.arange(20).reshape((4,5))
print(m)

print(m.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [51]:
v = np.random.randn(4, 4)
print(v)

print(v > 0)

z = np.where(v<0, -2, 2)
print(z)

[[ 1.40193629 -0.07382171 -0.32077743 -0.87542978]
 [ 0.27774755  1.60364317  0.76299118 -0.93944971]
 [ 0.56045627  0.74341633  1.24486581  1.52319524]
 [-0.45240091 -0.89785532  0.04871959  0.29619166]]
[[ True False False False]
 [ True  True  True False]
 [ True  True  True  True]
 [False False  True  True]]
[[ 2 -2 -2 -2]
 [ 2  2  2 -2]
 [ 2  2  2  2]
 [-2 -2  2  2]]
